# Generated by Django 5.0.1 on 2024-01-10 18:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32639)),
                ('fid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('navahi', models.DecimalField(decimal_places=0, max_digits=10)),
                ('area', models.FloatField()),
                ('fid1', models.DecimalField(decimal_places=0, max_digits=10)),
                ('latlon', models.CharField(max_length=255)),
                ('nahieid', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('population', models.FloatField()),
                ('objectid', models.FloatField()),
                ('unqid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pg_dump',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geo_fance', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TehranArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.BigIntegerField()),
                ('geo_fanc', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('navahi', models.SmallIntegerField()),
                ('zone', models.SmallIntegerField()),
                ('section', models.SmallIntegerField()),
                ('geo', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
