# Generated by Django 5.0.1 on 2024-01-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='TehranArea',
        ),
    ]
